{% set name = "pivy" %}
{% set version = "0.6.10" %}

{% if qt is undefined %}
{% set qt = "6" %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}.tar.gz
  url: https://github.com/coin3d/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7b409816c9fad84cf94f93659281f9dd2501d285eb2fc609e9401a3d004ce723
  patches:
    - patches/windows_cmake_install_path_fix.patch

build:
  number: 1
  string: py{{ CONDA_PY }}qt{{ qt }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script_env:
  {% if qt|int >=6 %}
    - USE_QT6=1
  {% else %}
    - USE_QT6=0
  skip: true  # [py>311]
  {% endif %}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - {{ cdt('mesa-libgl-devel') }}          # [linux]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - msinttypes                             # [win]
    - cmake
    - ninja
    - swig
  host:
    - python
    - coin3d
  {% if qt|int >=6 %}
    - qt6-main
    - soqt6
  {% else %}
    - qt-main
    - soqt
  {% endif %}
  run:
    - python

test:
  imports:
    - pivy.coin
    - pivy.gui.soqt

about:
  home: https://github.com/FreeCAD/pivy
  license: ISC
  license_file: LICENSE
  summary: python bindings to coin3d.
  doc_url: https://github.com/FreeCAD/pivy
  dev_url: https://github.com/FreeCAD/pivy

extra:
  recipe-maintainers:
    - looooo
