{% set name = "pivy" %}
{% set version = "0.6.5a2" %}
{% set sha256 = "49abea5cd62501e0dd36182dc8244c26be3de3c9707aaa11148dcc1f0faf3364" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}.tar.gz
    url: https://github.com/FreeCAD/pivy/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - c++17.patch

build:
    number: 3

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - msinttypes  # [win]
        - cmake
        - swig
    host:
        - python
        - coin3d
        - soqt
        - qt
        - colorama
    run:
        - python
        - coin3d
        - qt
        - pyside2
        - soqt

test:
    imports:
        - pivy.coin
        - pivy.gui.soqt

about:
    home: https://github.com/FreeCAD/pivy
    license: ISC
    license_file: LICENSE
    summary: python bindings to coin3d.
    doc_url: https://github.com/FreeCAD/pivy
    dev_url: https://github.com/FreeCAD/pivy

extra:
    recipe-maintainers:
        - looooo
