{% set name = "pivy" %}
{% set version = "0.6.4" %}
{% set sha256 = "0b09bc80007b61680ce13b2dd348da6fbaf19795be9a08eeb019ea2a1f51f97e" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}.tar.gz
    url: https://github.com/FreeCAD/pivy/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - win.patch  # [win]


build:
    number: 0

requirements:
    build:
        - {{ compiler("cxx") }}
        - msinttypes  # [win]
        - cmake
        - swig
    host:
        - python
        - coin3d
        - soqt
        - qt
        - colorama
    run:
        - python
        - coin3d
        - qt
        - pyside2
        - soqt

test:
    imports:
        - pivy.coin
        - pivy.gui.soqt

about:
    home: https://github.com/FreeCAD/pivy
    license: ISC
    license_file: LICENSE
    summary: python bindings to coin3d.
    doc_url: https://github.com/FreeCAD/pivy
    dev_url: https://github.com/FreeCAD/pivy

extra:
    recipe-maintainers:
        - looooo
