{% set name = "pivy" %}
{% set version = "0.6.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}.tar.gz
  url: https://github.com/coin3d/pivy/archive/conda-py311%2C-py312.tar.gz
  sha256: c443dd7dd724b0bfa06427478b9d24d31e0c3b5138ac5741a2917a443b28f346

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - msinttypes      # [win]
    - cmake
    - ninja
    - swig
  host:
    - python
    - coin3d
    - soqt      # [py < 312]
    - qt-main   # [py < 312]
    - soqt6     # [py >= 312]
    - qt6-main  # [py >= 312]
  run:
    - python
    - coin3d
    - qt-main   # [py < 312]
    - soqt      # [py < 312]
    - pyside2   # [py < 312]
    - qt6-main  # [py >= 312]
    - soqt6     # [py >= 312]
    - pyside6   # [py >= 312]
    - soqt

test:
  imports:
    - pivy.coin
    - pivy.gui.soqt

about:
  home: https://github.com/FreeCAD/pivy
  license: ISC
  license_file: LICENSE
  summary: python bindings to coin3d.
  doc_url: https://github.com/FreeCAD/pivy
  dev_url: https://github.com/FreeCAD/pivy

extra:
  recipe-maintainers:
    - looooo
