{% set name = "pivy" %}
{% set version = "0.6.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}.tar.gz
  url: https://github.com/coin3d/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: c207f5ed73089b2281356da4a504c38faaab90900b95639c80772d9d25ba0bbc

build:
  number: 0
  script_env:
    - USE_QT6=1  # [py >= 312]
    - USE_QT6=0  # [py < 312]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - msinttypes      # [win]
    - cmake
    - ninja
    - swig
  host:
    - python
    - coin3d
    - soqt      # [py < 312]
    - qt-main   # [py < 312]
    - soqt6     # [py >= 312]
    - qt6-main  # [py >= 312]
  run:
    - python
    - {{ pin_compatible('coin3d', max_pin='x.x') }}
    - qt-main   # [py < 312]
    - {{ pin_compatible('soqt', max_pin='x.x') }}  # [py < 312]
    - pyside2   # [py < 312]
    - qt6-main  # [py >= 312]
    - {{ pin_compatible('soqt6', max_pin='x.x') }}  # [py >= 312]
    - pyside6   # [py >= 312]
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }}  # [osx and x86_64]

test:
  imports:
    - pivy.coin
    - pivy.gui.soqt

about:
  home: https://github.com/FreeCAD/pivy
  license: ISC
  license_file: LICENSE
  summary: python bindings to coin3d.
  doc_url: https://github.com/FreeCAD/pivy
  dev_url: https://github.com/FreeCAD/pivy

extra:
  recipe-maintainers:
    - looooo
