{% set name = "pivy" %}
{% set version = "0.6.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}.tar.gz
  url: https://github.com/FreeCAD/pivy/archive/{{ version }}.tar.gz
  sha256: c207f5ed73089b2281356da4a504c38faaab90900b95639c80772d9d25ba0bbc

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - msinttypes      # [win]
    - cmake
    - ninja
    - swig
  host:
    - python
    - coin3d
    - soqt
    - qt-main
  run:
    - python
    - coin3d
    - qt-main
    - pyside2
    - soqt

test:
  imports:
    - pivy.coin
    - pivy.gui.soqt

about:
  home: https://github.com/FreeCAD/pivy
  license: ISC
  license_file: LICENSE
  summary: python bindings to coin3d.
  doc_url: https://github.com/FreeCAD/pivy
  dev_url: https://github.com/FreeCAD/pivy

extra:
  recipe-maintainers:
    - looooo
