{% set name = "pivy" %}
{% set version = "0.6.5a3" %}
{% set sha256 = "f28ba2ea9d1fc6308ed9fd6b1e40113cfd26e0790be1386fa940802b505bf44f" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}.tar.gz
    url: https://github.com/FreeCAD/pivy/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - msinttypes  # [win]
        - cmake
        - swig
    host:
        - python
        - coin3d
        - soqt
        - qt
        - colorama  # [not win]   
    run:
        - python
        - coin3d
        - qt
        - pyside2
        - soqt

test:
    imports:
        - pivy.coin
        - pivy.gui.soqt

about:
    home: https://github.com/FreeCAD/pivy
    license: ISC
    license_file: LICENSE
    summary: python bindings to coin3d.
    doc_url: https://github.com/FreeCAD/pivy
    dev_url: https://github.com/FreeCAD/pivy

extra:
    recipe-maintainers:
        - looooo
