appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IkAU4X3e7NQmCAcndy63n8wGpntCXcqi9wrV3HMIQF9j1Roo1ZRjPZjylKMP8WNnTAhWo8rOMDHSgqdYYgp7GA2n1mCBhC6MtQaPQo0VMZ5axzPJOcIfarT305L9nGSPGbAry5zCB9H9dtRp1pN9cpXhZZTmf5PqB3v7Wwetbrf+GzGTfnqeX0gE9VOarfnxNQOZPgt2zd3qjfLbb1qThKBRkTHvf0WxunjSFakRDlEFHKtrhQaNmPb0YUW29Zu0Umbfl6QubD4De4+8Xg4rjeLE5jAmIxyFkov5q3vDuXttjek37yXd9mH7JRF2Z+i59ZCxic9hN9xDfJgZUmZ9ce8CYv+gECLaz0cvaaw7SvpbvK97gM+aOdtiBEOEXre4p9GCKgUxTb16Dht+RUdH6F07/bbNUMv5MCLf4cqIpnT5XDymX52bAS1A9F1PgldF/ljDDrefbQ9I+3X3iZuYUa+udaeZeUb4kw8bRtFLO1VNI4KALAoa73aQSvYbLMAfVrud03dXKRslcnlw/6R+NkyDCwD5FYfCaCDrM83mkhiNNMiQ0y5cRnuBsnfaN9aH2IZM16bmdt8zKj5ZKSBDrKdw/cTCbaoq26gBObOfLeShuNNzAu1WSzRdfFtOTQX6IwvUjh7pANIpWXCowPI5DZvU7Svsp7pe035ii6QuITU=}
